import { ImplementationPath } from './types'

export const implementationPaths: ImplementationPath[] = [
  {
    id: 'content-engine',
    name: 'The Content Engine',
    role: 'Marketing',
    focus: 'Content creation pipeline with Claude',
    description: 'Build a systematic content operation — from ideation through multi-channel distribution — using Claude as your editorial team.',
    products: ['Chat', 'CoWork', 'Code'],
    subscriptionTier: 'Claude Pro ($20/mo) → Claude Max ($100/mo) when ready for Code',
    weeks: [
      { week: 1, title: 'Foundation', tasks: ['Set up a Claude Chat Project with your brand voice guide', 'Master the RCTFC prompt framework', 'Create your first content piece with Claude'] },
      { week: 2, title: 'System Building', tasks: ['Build a Brand Voice skill', 'Create a Content Repurposer skill', 'Set up your content pipeline: blog → social → email'] },
      { week: 3, title: 'Automation', tasks: ['Try Claude Code for batch content operations', 'Connect your email platform via API', 'Build a weekly content workflow'] },
      { week: 4, title: 'Scale', tasks: ['Create a full content calendar with Claude', 'Set up team CoWork for collaborative content', 'Review and refine your skills based on output quality'] },
    ],
    topPlaybooks: ['writing/content-creation-pipeline', 'marketing/brand-voice-system', 'marketing/campaign-brief-multi-channel', 'writing/editing-voice-matching', 'skills/building-your-first-skill'],
    starterPrompts: [
      'You are my content strategist. Here is my brand voice guide: [paste guide]. I need to create a blog post about [topic] that matches this voice exactly. Start by asking me 3 clarifying questions about the angle.',
      'Repurpose this blog post into: 1) A LinkedIn post (hook + 3 key insights + CTA), 2) A Twitter thread (7 tweets), 3) An email newsletter intro (3 paragraphs). Maintain the same voice throughout.',
    ],
  },
  {
    id: 'revenue-architect',
    name: 'The Revenue Architect',
    role: 'Sales',
    focus: 'Outbound, proposals, CRM automation',
    description: 'Transform your sales process with AI-powered research, proposal generation, and pipeline management.',
    products: ['Chat', 'Code'],
    subscriptionTier: 'Claude Pro ($20/mo) → Claude Max ($100/mo) for CRM automation',
    weeks: [
      { week: 1, title: 'Research & Prep', tasks: ['Master pre-call research prompts', 'Build a prospect analysis template', 'Create your first AI-assisted proposal'] },
      { week: 2, title: 'Proposals & Playbooks', tasks: ['Set up a Proposal Writer skill with your pricing and terms', 'Build an objection response library', 'Create proposal templates for each deal type'] },
      { week: 3, title: 'CRM Integration', tasks: ['Connect your CRM with Claude Code', 'Build a deal analysis workflow', 'Automate post-call CRM updates'] },
      { week: 4, title: 'Pipeline Intelligence', tasks: ['Set up win/loss analysis automation', 'Build a weekly pipeline review workflow', 'Create an outbound sequence generator'] },
    ],
    topPlaybooks: ['sales/pre-call-research-prep', 'sales/proposals-sows', 'sales/outbound-at-scale', 'sales/crm-integration-enrichment', 'code-for-operators/connect-business-tools'],
    starterPrompts: [
      'Research this company for my sales call tomorrow: [company name/URL]. I need: 1) Company overview and recent news, 2) Key stakeholders and their likely priorities, 3) Potential pain points based on their industry, 4) Three conversation starters based on their recent activity.',
      'Create a proposal for [client name]. Context: [paste call notes]. Our pricing: [paste pricing]. Include: executive summary, proposed solution, timeline, investment, and next steps. Match a professional but warm tone.',
    ],
  },
  {
    id: 'data-operator',
    name: 'The Data Operator',
    role: 'Finance',
    focus: 'Reporting, analysis, modeling',
    description: 'Turn Claude into your personal analyst — building models, automating reports, and translating data into decisions.',
    products: ['Chat', 'Code'],
    subscriptionTier: 'Claude Pro ($20/mo) → Claude Max ($100/mo) for Excel and reporting automation',
    weeks: [
      { week: 1, title: 'Analysis Basics', tasks: ['Learn to upload and analyze data in Claude Chat', 'Master variance analysis prompts', 'Create your first board narrative from raw data'] },
      { week: 2, title: 'Model Building', tasks: ['Build your first Excel model with Claude Code', 'Create a monthly reporting template', 'Set up a Financial Report Narrator skill'] },
      { week: 3, title: 'Automation', tasks: ['Connect your data sources (Stripe, analytics)', 'Automate a weekly report generation', 'Build a cohort analysis workflow'] },
      { week: 4, title: 'Advanced Modeling', tasks: ['Create scenario models (bull/base/bear)', 'Build a sensitivity analysis template', 'Set up board deck narrative automation'] },
    ],
    topPlaybooks: ['finance/excel-models-plain-english', 'finance/monthly-reporting', 'finance/cohort-analysis-unit-economics', 'finance/sensitivity-scenario-modeling', 'code-for-operators/connect-business-tools'],
    starterPrompts: [
      'I have monthly revenue data for the last 12 months: [paste data]. Create a variance analysis comparing each month to the prior month and to the same month last year. Explain any significant variances in plain English suitable for a board deck.',
      'Build me an Excel model for [describe scenario]. Include these assumptions: [list]. I need real Excel formulas (=SUM, =IF, =VLOOKUP, etc.), not just values. Output as a structured table I can paste into a spreadsheet.',
    ],
  },
  {
    id: 'systems-builder',
    name: 'The Systems Builder',
    role: 'Operations',
    focus: 'SOPs, processes, knowledge bases',
    description: 'Design how work gets done — documented procedures, connected tools, and automated workflows.',
    products: ['Chat', 'CoWork', 'Code'],
    subscriptionTier: 'Claude Pro ($20/mo) → Team plan for CoWork → Max for Code automation',
    weeks: [
      { week: 1, title: 'Documentation', tasks: ['Turn 3 tribal knowledge processes into SOPs', 'Master the SOP generation prompts', 'Create a project kickoff template'] },
      { week: 2, title: 'Knowledge Base', tasks: ['Set up CoWork as a team knowledge base', 'Build a Process Auditor skill', 'Document your top 5 workflows'] },
      { week: 3, title: 'Tool Integration', tasks: ['Connect your project management tool with Claude Code', 'Automate meeting notes to task creation', 'Build a workflow automation for your most repetitive process'] },
      { week: 4, title: 'Scale', tasks: ['Create a skills library for your team', 'Build cross-tool automation workflows', 'Set up a weekly process improvement review'] },
    ],
    topPlaybooks: ['operations/sop-machine', 'operations/tool-integration-automation', 'operations/project-management-ai', 'code-for-operators/skills-teach-workflows', 'skills/composing-skill-systems'],
    starterPrompts: [
      'I need to document this process as an SOP. Here are my rough notes: [paste notes]. Create a step-by-step procedure with: purpose, scope, prerequisites, detailed steps (with decision points), and common troubleshooting issues.',
      'Analyze this workflow for bottlenecks and improvement opportunities: [describe current workflow]. For each improvement, estimate the time savings and implementation difficulty (low/medium/high).',
    ],
  },
  {
    id: 'ai-first-founder',
    name: 'The AI-First Founder',
    role: 'Founder/CEO',
    focus: 'Cross-functional, strategy + execution',
    description: 'Use AI as a force multiplier across every function — from strategy to operations to team enablement.',
    products: ['Chat', 'Code'],
    subscriptionTier: 'Claude Max ($100/mo) for full Code access',
    weeks: [
      { week: 1, title: 'Personal Productivity', tasks: ['Set up Claude Chat with your company context as a Project', 'Master email triage and decision journaling', 'Create a weekly CEO review workflow'] },
      { week: 2, title: 'Claude Code Foundation', tasks: ['Install Claude Code and set up VSCode', 'Write your CLAUDE.md business operating system file', 'Build your first 3 commands for recurring tasks'] },
      { week: 3, title: 'Business Integration', tasks: ['Connect your key business tools (Stripe, CRM, analytics)', 'Build a weekly metrics dashboard command', 'Create decision framework commands'] },
      { week: 4, title: 'Team Enablement', tasks: ['Create a plan for rolling out AI to your team', 'Set up CoWork for your team', 'Build a skills library your team can use'] },
    ],
    topPlaybooks: ['foundations/how-claude-thinks', 'code-for-operators/what-claude-code-is', 'code-for-operators/claude-md-business-os', 'leadership/rolling-out-ai-team', 'personal/decision-journals'],
    starterPrompts: [
      'You are my strategic thinking partner. I\'m the CEO of [company description]. Here\'s my current situation: [describe]. I need to make a decision about [topic]. Don\'t validate my thinking — challenge my assumptions. Ask me the questions I\'m not asking myself.',
      'Review my calendar and commitments for this week: [paste]. As my chief of staff, help me: 1) Identify which meetings I should actually attend vs. delegate, 2) Prep notes for the top 3 most important meetings, 3) Flag any conflicts or missing follow-ups.',
    ],
  },
  {
    id: 'product-leader',
    name: 'The Product Leader',
    role: 'Product',
    focus: 'Specs, research synthesis, roadmaps',
    description: 'Ship better products faster — from competitor analysis to specs to stakeholder communication.',
    products: ['Chat', 'CoWork'],
    subscriptionTier: 'Claude Pro ($20/mo) → Team plan for CoWork',
    weeks: [
      { week: 1, title: 'Research & Analysis', tasks: ['Run your first competitive teardown with Claude', 'Synthesize 3 user interviews in one session', 'Create a PRD from rough notes'] },
      { week: 2, title: 'Specification Mastery', tasks: ['Build a PRD Writer skill with your template', 'Master the multi-turn refinement workflow', 'Create specs for your next 3 features'] },
      { week: 3, title: 'Communication', tasks: ['Set up sprint → stakeholder update automation', 'Build a roadmap communication template', 'Create a technical decision translator workflow'] },
      { week: 4, title: 'System', tasks: ['Set up CoWork as your product knowledge base', 'Build a feature prioritization framework', 'Create a quarterly planning workflow'] },
    ],
    topPlaybooks: ['product/competitive-feature-teardowns', 'product/prd-spec-writing', 'product/user-research-synthesis', 'product/sprint-planning-roadmap', 'foundations/projects-memory-skills'],
    starterPrompts: [
      'I need a competitive teardown of [competitor product/URL]. Analyze: 1) Key features and capabilities, 2) How it compares to our product [describe yours], 3) Features they have that we don\'t (gap analysis), 4) Estimated effort to close each gap (T-shirt sizing: S/M/L/XL).',
      'Here are transcripts from 5 user interviews about [topic]: [paste]. Synthesize into: 1) Top 5 themes with supporting quotes, 2) Unmet needs ranked by frequency, 3) Suggested feature priorities, 4) Surprises or contradictions.',
    ],
  },
  {
    id: 'team-multiplier',
    name: 'The Team Multiplier',
    role: 'Leadership',
    focus: 'People management + team AI rollout',
    description: 'Make your team stronger with AI — from better 1:1s to rolling out Claude across your org.',
    products: ['Chat', 'CoWork'],
    subscriptionTier: 'Claude Pro ($20/mo) → Team plan for CoWork',
    weeks: [
      { week: 1, title: 'Management Basics', tasks: ['Create 1:1 agendas with Claude for your next round', 'Draft performance review outlines for your team', 'Build a difficult conversation prep template'] },
      { week: 2, title: 'Goal Setting', tasks: ['Facilitate OKR setting with Claude', 'Create alignment checks across team goals', 'Build a progress tracking workflow'] },
      { week: 3, title: 'Team AI Rollout', tasks: ['Map use cases to team members and Claude products', 'Create an AI adoption plan for your team', 'Set up CoWork for your team\'s shared knowledge'] },
      { week: 4, title: 'Scale & Sustain', tasks: ['Build skills for common team workflows', 'Create an onboarding program for new hires using AI', 'Set up monthly AI usage review'] },
    ],
    topPlaybooks: ['leadership/rolling-out-ai-team', 'leadership/performance-reviews', 'leadership/one-on-one-system', 'leadership/okrs-goal-setting', 'code-for-operators/what-claude-code-is'],
    starterPrompts: [
      'I need to write a performance review for [name], [role]. Here are my notes from the past quarter: [paste notes]. Write a balanced review that: 1) Leads with specific accomplishments, 2) Identifies 2-3 growth areas with concrete examples, 3) Sets clear expectations for next quarter. Tone: direct but supportive.',
      'I need to have a difficult conversation with [name] about [topic]. Help me: 1) Structure the conversation (opening, key points, listening phase, resolution), 2) Prepare for likely reactions, 3) Draft the key phrases I should use. I want to be direct but empathetic.',
    ],
  },
  {
    id: 'efficiency-machine',
    name: 'The Efficiency Machine',
    role: 'IC',
    focus: 'Personal productivity + automation',
    description: 'Do more with less — email triage, research, admin, and better decision-making.',
    products: ['Chat'],
    subscriptionTier: 'Claude Pro ($20/mo)',
    weeks: [
      { week: 1, title: 'Email & Communication', tasks: ['Set up an email triage workflow', 'Master reply drafting with context', 'Build a meeting notes processor'] },
      { week: 2, title: 'Research & Learning', tasks: ['Use Claude to synthesize a book or long article', 'Create a research workflow for your domain', 'Build a personal knowledge capture system'] },
      { week: 3, title: 'Decision Making', tasks: ['Start a decision journal with Claude', 'Master the pre-mortem analysis technique', 'Create a weekly reflection template'] },
      { week: 4, title: 'Advanced Productivity', tasks: ['Build custom skills for your top 3 recurring tasks', 'Set up a Project with your professional context', 'Create a daily planning workflow'] },
    ],
    topPlaybooks: ['personal/email-communication-triage', 'personal/learning-research', 'personal/decision-journals', 'foundations/anatomy-of-a-prompt', 'foundations/common-mistakes'],
    starterPrompts: [
      'Here are 15 emails I need to respond to: [paste]. For each one: 1) Priority level (urgent/important/low), 2) Suggested action (reply/delegate/defer/archive), 3) Draft reply if action is "reply" — keep it concise and professional.',
      'I need to make a decision about [topic]. Walk me through a structured analysis: 1) What are my options? 2) What are the key criteria for this decision? 3) What\'s the best case, worst case, and most likely outcome for each option? 4) What am I probably not considering?',
    ],
  },
]
