import { Section } from './types'

export const sections: Section[] = [
  {
    id: 'foundations',
    title: 'Foundations',
    description: 'The mental models that make everything else click.',
    icon: '🧠',
    href: '/claude-playbook/foundations',
    playbookCount: 7,
  },
  {
    id: 'writing',
    title: 'Writing & Communication',
    description: 'Email, docs, content, and everything written.',
    icon: '✍️',
    href: '/claude-playbook/writing',
    playbookCount: 6,
  },
  {
    id: 'marketing',
    title: 'Marketing & Content',
    description: 'Campaigns, ads, SEO, social, and brand voice.',
    icon: '📣',
    href: '/claude-playbook/marketing',
    playbookCount: 7,
  },
  {
    id: 'sales',
    title: 'Sales & Revenue',
    description: 'Pre-call prep, proposals, outbound, CRM, and revenue ops.',
    icon: '💰',
    href: '/claude-playbook/sales',
    playbookCount: 7,
  },
  {
    id: 'operations',
    title: 'Operations & Processes',
    description: 'SOPs, project management, knowledge bases, and automation.',
    icon: '⚙️',
    href: '/claude-playbook/operations',
    playbookCount: 6,
  },
  {
    id: 'finance',
    title: 'Finance & Reporting',
    description: 'Excel models, reporting, board decks, and scenario analysis.',
    icon: '📊',
    href: '/claude-playbook/finance',
    playbookCount: 7,
  },
  {
    id: 'product',
    title: 'Product & Engineering Leadership',
    description: 'Teardowns, specs, research synthesis, and sprint planning.',
    icon: '🔧',
    href: '/claude-playbook/product',
    playbookCount: 5,
  },
  {
    id: 'leadership',
    title: 'Leadership & Management',
    description: 'Reviews, 1:1s, difficult conversations, and team AI rollout.',
    icon: '👥',
    href: '/claude-playbook/leadership',
    playbookCount: 6,
  },
  {
    id: 'personal',
    title: 'Personal Productivity',
    description: 'Email triage, research, admin, and decision-making.',
    icon: '⚡',
    href: '/claude-playbook/personal',
    playbookCount: 5,
  },
  {
    id: 'code-for-operators',
    title: 'Claude Code for Operators',
    description: 'The most differentiated section. Claude Code for non-developers.',
    icon: '🖥️',
    href: '/claude-playbook/code-for-operators',
    playbookCount: 8,
  },
  {
    id: 'skills',
    title: 'Skills Deep-Dive',
    description: 'Build, install, and compose Claude Skills for any discipline.',
    icon: '🎯',
    href: '/claude-playbook/skills',
    playbookCount: 6,
  },
  {
    id: 'case-studies',
    title: 'Case Studies',
    description: 'Two real-world Claude Code setups from a non-developer.',
    icon: '📋',
    href: '/claude-playbook/case-studies',
    playbookCount: 2,
  },
]
